const POPULATE_MESSAGES = 'POPULATE_MESSAGES'
const LOAD_MESSAGE      = 'LOAD_MESSAGE'
const SET_CURRENT_USER  = 'SET_CURRENT_USER'

export {
  POPULATE_MESSAGES,
  LOAD_MESSAGE,
  SET_CURRENT_USER
}
